const {test}=require('node:test'),assert=require('node:assert/strict'),H=require('../js/income-history'),E=require('../js/engine'),S=require('../js/save'),{ready}=require('./current-fixtures.cjs'),{harness}=require('./app-harness.cjs');
test('actual revenue windows include idle time, rare boss clears, all quests and measured startup time',()=>{const h=new H(0);h.add('boss',120000,10000);h.add('mob',300,20000);assert.equal(h.read(300,20000).rate,6015);assert.equal(h.read(60,30000).rate,4010);assert.equal(h.read(60,80000).total,0);assert.equal(h.read(300,80000).total,120300);assert.equal(h.read(1800,600000).rate,200.5);assert.equal(h.read(1800,1810000).total,300);assert.equal(h.read(1800,1820000).rate,0);assert.equal(h.buckets.length,1801);});
test('bounded buckets aggregate multiple awards and reset unknown offline interval',()=>{const h=new H(0);for(let n=0;n<36000;n++)h.add('q',2,n*1000);assert.equal(h.buckets.filter(Boolean).length,1801);assert.equal(h.read(1800,35999000).total,3600);h.reset(36000000);assert.equal(h.read(60,36001000).rate,0);assert.equal(h.read(300,36001000).elapsed,1);});
test('income observer reports exact capped gains without refunds, spending or state schema changes',()=>{const s=ready(['meta']),h=new H(0),beforeKeys=Object.keys(s);E.observeIncome((id,amount)=>h.add(id,amount,1000));E.grantIncome(s,500,'questReward');E.grantIncome(s,30,'jewelSideIncome');E.grantIncome(s,100,'refund');s.factors-=50;assert.equal(h.read(60,2000).total,530);assert.deepEqual(Object.keys(s),beforeKeys);E.refreshPerkUnlocks(s);assert.deepEqual(S.decode(S.encode(s)),s);E.observeIncome(null);});
test('hidden details remain untouched, opening is fresh, real awards appear, and recovery never spikes income',async()=>{const s=ready(['meta']);s.levels.meta=20;s.paused=true;const h=harness(s);assert.equal(h.get('ability-value-power-meta').textContent,'');assert.equal(h.get('quest-hp-mohicans').textContent,'');h.advance(2000);assert.equal(h.get('ability-value-power-meta').textContent,'');h.openAbility('meta');assert.equal(h.get('ability-value-power-meta').textContent,'20');h.closeAbility();h.click('tab-quests');assert.notEqual(h.get('quest-hp-mohicans').textContent,'');assert.equal(h.income().rate,0);});
test('DPS and public engine contain no revenue simulation API',()=>{assert.equal(E.expectedIncome,undefined);assert.equal(E.totalIncome,undefined);const s=ready(['meta']);const before=structuredClone(s);assert.ok(E.totalDps(s)>=0);assert.deepEqual(s,before);});
test('real UI income equals cumulative awarded income and survives spending without subtraction',()=>{const s=ready(['meta']);s.levels.meta=260;const h=harness(s);h.advance(4000);h.click('save-now');const actual=h.saved();assert.equal(h.income().total,actual.earned-s.earned);assert.ok(h.income().total>0);assert.equal(h.income().elapsed,4);h.click('pause');h.advance(4000);assert.equal(h.income().total,actual.earned-s.earned);assert.equal(h.income().elapsed,8);});

test('offline recovery discards telemetry for the unknown interval, while retaining earned game rewards',async()=>{const s=ready(['meta']);let finish;const h=harness(s,undefined,{recovery:{run(_e,state){return new Promise(resolve=>{finish=()=>resolve({...state,factors:state.factors+100000,earned:state.earned+100000});});}}});h.stall(10000);finish();await new Promise(resolve=>setImmediate(resolve));assert.equal(h.income().total,0);assert.equal(h.income().elapsed,0);assert.equal(h.saved().earned,s.earned+100000);});
test('hidden purchase lists do no quote calculations on startup or repeated balance changes',()=>{let count=0;const original=E.purchaseQuote;E.purchaseQuote=(...args)=>{count++;return original(...args);};try{const s=ready(['meta']);s.levels.meta=260;const h=harness(s);h.advance(3000);h.click('attack');assert.equal(count,0);h.openAbility('meta');assert.ok(count>0);const before=count;h.advance(3000);assert.equal(count,before);}finally{E.purchaseQuote=original;}});
