const {test}=require('node:test'),assert=require('node:assert/strict');
const D=require('../js/data'),E=require('../js/engine'),S=require('../js/save');
const UI=require('../js/display');
test('large AP balances keep stateful cloud actions bounded and retain unprocessed AP',()=>{const s=ready(['tordeliese']);s.questLevels.ozmorn=200;s.questActiveLevels.ozmorn=200;E.setQuestLevel(s,'ozmorn',199);E.setQuestLevel(s,'ozmorn',200);s.actionPoints.tordeliese=1e12;const events=E.advance(s,1,faces(4));assert.ok(s.actionPoints.tordeliese>1e11);assert.ok(events.length<=125);assert.doesNotThrow(()=>S.encode(s));});
const c=id=>D.characters.find(c=>c.id===id),faces=(...v)=>()=>((v.shift()??4)-.5)/6;
function ready(ids=[]){const s=E.createState(1000);s.factors=1e9;for(const id of ids)s.levels[id]=1;E.refreshQuestUnlocks(s);E.setFormation(s,'ozmorn',ids);E.selectSession(s,'ozmorn');E.ensureEnemies(s);return s;}
function spawn(s,count=1){for(let i=0;i<count;i++){if(i)E.selectEnemy(s,s.enemies[0].id);E.click(s,faces(4));}return s.enemies.filter(e=>e.kind==='kogumo'&&e.hp>0);}
function pending(s,slot,kind='attack'){s.enemies[slot].pendingAttack={targetId:'meta',remaining:.1,count:1,kind};return E.advance(s,.1,faces(4),true);}
test('quest unlock, stats, growth and reward follow supplied values',()=>{const s=E.createState();assert.equal(E.isQuestUnlocked(s,'ozmorn'),false);s.factors=1e6;E.refreshQuestUnlocks(s);s.factors=0;assert.equal(E.isQuestUnlocked(s,'ozmorn'),true);const q=E.getSession(s,'ozmorn');assert.equal(q.hp,130);assert.equal(q.reward,50);assert.equal(q.ignoreDefense,true);assert.deepEqual(q.actionDice,{flat:7,dice:2});assert.equal(q.evasion.flat,9);s.questLevels.ozmorn=2;assert.equal(E.getSession(s,'ozmorn').hp,Math.floor(130*E.T.enemyDurability(1,'vitality')/100));assert.equal(E.getSession(s,'ozmorn').reward,63);});
test('nonlethal hits create two independent clouds, then merge into the weaker one',()=>{const s=ready();assert.equal(E.livingEnemies(s).length,1);assert.equal(E.actionThreshold(s),28);spawn(s,3);const clouds=s.enemies.slice(1);assert.deepEqual(clouds.map(e=>e.hp),[2,1]);assert.deepEqual(clouds.map(e=>e.creationDamage),[1,1]);assert.equal(E.getSession(s).traits.includes('swarm'),true);assert.equal(E.enemySpec(s,clouds[0]).accuracy.flat,1);assert.equal(E.enemySpec(s,clouds[0]).accuracy.dice,2);assert.equal(E.enemyMaxHP(s,clouds[0]),2);assert.notEqual(clouds[0].id,clouds[1].id);assert.equal(E.actionThreshold(s),26);});
test('poison damage does not create or strengthen a cloud',()=>{const s=ready();s.enemies[0].poisonDamage=4;s.poisonDamage=4;const events=E.click(s,faces(4));assert.equal(events.filter(e=>e.type==='enemySummon').length,1);assert.equal(s.enemies[1].hp,1);assert.equal(s.enemies[2].hp,0);assert.equal(s.enemies[0].hp,125);});
test('lethal or knockout hit does not spawn; boss defeat clears clouds and pays once',()=>{for(const knockout of [false,true]){const s=ready();spawn(s,2);s.enemies[0].hp=knockout?5:1;E.selectEnemy(s,s.enemies[0].id);const before=s.factors,events=E.click(s,faces(3));assert.equal(events.filter(e=>e.type==='enemySummon').length,0);assert.equal(s.enemies[0].hp,0);assert.equal(s.enemies.slice(1).every(e=>e.hp===0),true);assert.equal(s.factors-before,50);assert.equal(E.isWaiting(s),true);assert.equal(s.respawnSeconds,5);assert.equal(E.getSession(s).traits.includes('swarm'),false);E.advance(s,5,faces(4));assert.equal(s.enemies[0].hp,130);assert.equal(E.livingEnemies(s).length,1);}});
test('cloud kills have no reward, no clear proc and never respawn on their own',()=>{const s=ready();spawn(s);const cloud=s.enemies[1];E.selectEnemy(s,cloud.id);const before=s.factors,events=E.click(s,faces(4));assert.equal(events.filter(e=>e.type==='clear').length,0);assert.equal(s.factors,before);assert.equal(s.kills,0);assert.equal(cloud.hp,0);assert.equal(cloud.respawnSeconds,0);E.advance(s,10,faces(4));assert.equal(cloud.hp,0);assert.equal(E.getSession(s).traits.includes('swarm'),false);assert.doesNotThrow(()=>S.encode(s));});
test('absorb resolves after animation, uses current HP, caps HP, cancels minion attacks',()=>{const s=ready(['meta']);spawn(s,3);s.enemies[1].hp=6;s.enemies[2].hp=2;s.enemies[0].hp=128;E.selectEnemy(s,null);s.enemies[1].pendingAttack={targetId:'meta',remaining:.2,count:1,kind:'flash'};s.enemies[0].pendingAttack={targetId:'meta',remaining:.1,count:1,kind:'absorb'};E.advance(s,.05,faces(4));assert.equal(s.enemies[0].hp,128);const events=E.advance(s,.05,faces(4));assert.equal(s.enemies[0].hp,130);assert.equal(events.find(e=>e.type==='enemyAbsorb').amount,2);assert.equal(s.enemies.slice(1).every(e=>!e.hp&&!e.pendingAttack),true);assert.ok(events.some(e=>e.type==='enemyCancel'));assert.equal(s.health.meta.hp,20);assert.doesNotThrow(()=>S.encode(s));});
test('boss chooses absorption only with adds and when the 20 percent roll succeeds',()=>{const s=ready(['meta']);spawn(s);s.enemies[0].actionPoints=E.actionThreshold(s);const before=s.health.meta.hp;const events=E.advance(s,1,()=>.1);const windup=events.find(e=>e.type==='enemyWindup'&&e.targetSlot===0);assert.equal(windup.kind,'absorb');assert.equal(s.health.meta.hp,before);});
test('flash removes AP after a hit, leaves HP and damage-income unchanged',()=>{const s=ready(['meta']);spawn(s);s.enemies[1].maxHP=s.enemies[1].creationDamage=s.enemies[1].hp=30;E.selectEnemy(s,null);s.actionPoints.meta=20;const before=s.health.meta.hp,events=pending(s,1,'flash');const hit=events.find(e=>e.type==='enemyAttack');assert.equal(hit.hit,true);assert.equal(hit.apDamage,true);assert.equal(s.health.meta.hp,before);assert.equal(s.actionPoints.meta,20-hit.damage);assert.equal(hit.hpBefore,hit.hpAfter);assert.doesNotThrow(()=>S.encode(s));});
test('flash can miss, and AP loss is bounded by available points',()=>{const s=ready(['meta']);spawn(s);s.actionPoints.meta=3;s.enemies[1].maxHP=s.enemies[1].creationDamage=30;s.enemies[1].hp=30;pending(s,1,'flash');assert.equal(s.actionPoints.meta,0);s.enemies[1].creationDamage=4;s.enemies[1].hp=4;s.actionPoints.meta=10;s.levels.meta=Math.max(s.levels.meta,51);const e=pending(s,1,'flash').find(e=>e.type==='enemyAttack');assert.equal(e.hit,false);assert.equal(s.actionPoints.meta,10);});
test('lightning penetrates armor and only damages after the attack timer ends',()=>{const s=ready(['meta']);s.levels.meta=Math.max(s.levels.meta,51);s.enemies[0].pendingAttack={targetId:'meta',remaining:.2,count:1,kind:'attack'};E.advance(s,.1,faces(4));assert.equal(s.health.meta.hp,20);const e=E.advance(s,.1,faces(4)).find(e=>e.type==='enemyAttack');assert.equal(e.damage,11);assert.equal(s.health.meta.hp,9);});
test('clouds use unscaled original evasion and independent statuses',()=>{const s=ready();spawn(s,3);assert.equal(E.targetEvasion({evasion:{flat:9,dice:1,multiplier:2}},s.enemies[1]).flat,1);assert.equal(E.targetEvasion({evasion:{flat:9,dice:1,multiplier:2}},s.enemies[1]).multiplier,undefined);assert.equal(E.targetDefense({defense:99},s.enemies[1]),0);s.enemies[1].evasionPenalty=6;s.enemies[1].evasionPenaltyTurns=2;assert.equal(E.targetEvasion({evasion:{flat:9,dice:1}},s.enemies[1]).flat,-5);assert.equal(E.targetEvasion({evasion:{flat:9,dice:1}},s.enemies[2]).flat,1);});
test('swarm area attacks activate only while a cloud is present',()=>{const s=ready(['meta']);s.levels.meta=125;s.purchasedPerks.meta=['metal-storm'];s.perkEnabled.meta=Object.fromEntries(s.purchasedPerks.meta.map(id=>[id,true]));assert.equal(E.attackProfile(s,c('meta')).areaAttack,false);spawn(s);assert.equal(E.attackProfile(s,c('meta')).areaAttack,true);E.selectEnemy(s,s.enemies[1].id);E.click(s,faces(4));assert.equal(E.attackProfile(s,c('meta')).areaAttack,false);});
test('summons and pending absorption survive save, session switch, offline processing',()=>{const s=ready(['meta']);spawn(s,3);E.selectEnemy(s,s.enemies[1].id);s.enemies[0].pendingAttack={targetId:'meta',remaining:.7,count:1,kind:'absorb'};const copy=S.decode(S.encode(s));assert.deepEqual(copy.enemies,s.enemies);E.selectSession(copy,'scarecrow');const loaded=S.decode(S.encode(copy));E.advance(loaded,.7,faces(4));E.selectSession(loaded,'ozmorn');assert.equal(E.livingEnemies(loaded).length,1);assert.equal(loaded.enemies[0].hp,130);assert.doesNotThrow(()=>S.encode(loaded));});
test('challenge changes clear summons/AP/status without healing allies',()=>{const s=ready(['meta']);spawn(s,2);s.health.meta.hp=10;s.actionPoints.meta=4;s.questActiveLevels.ozmorn=1;s.questLevels.ozmorn=2;E.setQuestLevel(s,'ozmorn',2);assert.equal(E.livingEnemies(s).length,1);assert.equal(s.enemies[0].hp,E.getSession(s).hp);assert.equal(s.health.meta.hp,10);assert.equal(s.actionPoints.meta,0);assert.doesNotThrow(()=>S.encode(s));});
test('existing v32 saves migrate without altering balances or rosters',()=>{const s=E.createState(1000);s.factors=32;const doc=JSON.parse(S.encode(s));doc.schemaVersion=32;const loaded=S.decode(JSON.stringify(doc));assert.equal(loaded.factors,32);assert.equal(loaded.questLevels.ozmorn,1);assert.equal(loaded.questUnlocks.ozmorn,false);});
test('reject forged summon kinds, excess HP and summon respawn/pending attacks while absent',()=>{const s=ready(['meta']);spawn(s);for(const mutate of [x=>x.enemies[1].kind='boss',x=>x.enemies[1].hp=100,x=>x.enemies[1].respawnSeconds=3,x=>{x.enemies[2].pendingAttack={targetId:'meta',remaining:.5,count:1,kind:'flash'};}]){const copy=structuredClone(s);mutate(copy);assert.throws(()=>S.encode(copy));}});
test('outdoor cycle progresses through dawn, day, dusk and night and crossfades continuously',()=>{const cycle=D.sceneCycle;assert.deepEqual([30,150,330,450].map(t=>UI.outdoorPhase(t,cycle).label),['朝焼け','昼','夕方','夜']);for(const end of [90,300,390,600]){const before=UI.outdoorPhase(end-.001,cycle),after=UI.outdoorPhase(end,cycle);assert.equal(before.to,after.from);assert.ok(before.blend>.999);assert.equal(after.blend,0);}const s=ready();s.sceneSeconds=599;E.advance(s,2,faces(4));assert.equal(s.sceneSeconds,1);assert.equal(S.decode(S.encode(s)).sceneSeconds,1);});
test('absorption consumes one action of a multi-action turn, not every action',()=>{const s=ready(['meta']);spawn(s);s.enemies[0].pendingAttack={targetId:'meta',remaining:.1,count:2,kind:'absorb'};const events=E.advance(s,.1,faces(4));assert.equal(events.filter(e=>e.type==='enemyAbsorb').length,1);assert.equal(events.filter(e=>e.type==='enemyAttack').length,1);assert.equal(s.health.meta.hp,5);});
