const {test}=require('node:test'),assert=require('node:assert/strict');
const D=require('../js/data'),E=require('../js/engine'),S=require('../js/save'),B=require('../js/battle-batch'),{harness}=require('./app-harness.cjs');
const c=id=>D.characters.find(c=>c.id===id),faces=(...v)=>()=>((v.shift()??4)-.5)/6;
function ready(ids=['meta'],q='mohican-solo'){const s=E.createState(1000);s.factors=1e15;for(const id of ids)s.levels[id]=1;E.refreshQuestUnlocks(s);E.setFormation(s,q,ids);E.selectSession(s,q);E.ensureEnemies(s);s.selectedCharacterId=ids[0];return s;}
function durable(s){s.questLevels[s.sessionId]=150;E.setQuestLevel(s,s.sessionId,150);return s;}
const attack=(s,r)=>E.click(s,r).find(e=>e.type==='attack');
test('AP uses lower median times two; excludes inert robot and includes downed and waiting slots',()=>{const s=ready(['meta'],'scarecrow');assert.equal(E.actionThreshold(s),30);s.health.meta.status='dying';assert.equal(E.actionThreshold(s),30);const x=ready(['meta','richter','waku'],'mohicans');assert.equal(E.actionThreshold(x),22);x.enemies[0].respawnSeconds=5;assert.equal(E.actionThreshold(x),22);});
test('plot armor uses armor Lv50 and rolls one extra action die per ally',()=>{const s=ready(['meta','max'],'scarecrow');s.actionLevels.max=50;s.purchasedPerks.max=['plot-armor'];assert.equal(E.actionPower(s,c('meta')),15);s.armorLevels.max=50;assert.equal(E.actionPower(s,c('meta')),18.5);assert.equal(E.actionPower(s,c('meta'),15,false,faces(2)),17);assert.equal(E.actionPower(s,c('meta'),15,false,faces(6)),21);assert.equal(E.enemyAttackSpec(s).sides,4);s.health.max.status='dying';assert.equal(E.actionPower(s,c('meta')),15);assert.equal(E.enemyAttackSpec(s).sides,6);});
test('meta new accuracy and chain perks use their own levels and retain full-metal attack bonus',()=>{const s=ready();s.levels.meta=100;s.accuracyLevels.meta=10;s.actionLevels.meta=50;s.purchasedPerks.meta=['full-metal-burst','lock-plus','spinning-rush'];assert.equal(E.accuracySpec(s,c('meta')).flat,26);assert.equal(E.stats(s,c('meta')).flat,8);assert.equal(E.attackProfile(s,c('meta')).extraAttackChance,.25);assert.equal(E.chainAttackCount(.25,()=>.95),3);s.actionLevels.meta=49;assert.equal(E.attackProfile(s,c('meta')).extraAttackChance,0);});
test('metal shield subtracts six on physical non-double hits, regardless of fumble or smash',()=>{
 function hit(withShield,rolls,q='mohican-solo'){const s=ready(['meta'],q);s.armorLevels.meta=25;if(withShield)s.purchasedPerks.meta=['metal-shield'];s.health.meta.hp=1000;s.enemies[0].pendingAttack={targetId:'meta',remaining:.1,count:1};const base=D.sessions.find(x=>x.id===q),original=base.attack;base.attack={...original,flat:100};try{return E.advance(s,.1,faces(...rolls)).find(e=>e.type==='enemyAttack');}finally{base.attack=original;}}
 // Fumble reduces evasion from 10 to9: enemy 14 remains a normal hit.
 let rolls=[4,1,1,6,6];assert.equal(hit(false,rolls).damage-hit(true,rolls).damage,6);
 // Two criticals produce a smash, but defender's exploding roll prevents double difference.
 rolls=[6,6,4,6,4,6,6,6];assert.equal(hit(true,rolls).smashCritical,1);assert.equal(hit(true,rolls).doubleHit,false);assert.equal(hit(false,rolls).damage-hit(true,rolls).damage,6);
 rolls=[6,6,4,2,6,6,6,6];assert.equal(hit(true,rolls).doubleHit,true);assert.equal(hit(false,rolls).damage,hit(true,rolls).damage);
 rolls=[4,4,6,6,6,6];assert.equal(hit(false,rolls,'dementor').damage,hit(true,rolls,'dementor').damage);
});
test('nextFrame applies next-evasion failure only after a hit, consumes once and does not stack',()=>{
 const s=ready(['waku']);s.levels.waku=100;s.purchasedPerks.waku=['next-frame'];s.enemies[0].hp=s.hp=1e6;
 // Six damage dice, hit/evasion, proc. Proc uses 0.0833 <10%.
 const first=attack(s,faces(4,4,4,4,4,4,4,4,1));assert.equal(first.hit,true);assert.equal(s.enemies[0].evasionFailure,true);
 s.purchasedPerks.waku=[];const forced=attack(s,faces(4,4,4,4,1,6,6,4));assert.equal(forced.hit,true);assert.equal(forced.forcedEvasionFailure,true);assert.equal(forced.doubleHit,false);assert.equal(s.enemies[0].evasionFailure,false);
 const miss=attack(s,faces(4,4,4,4,1,6,6,4));assert.equal(miss.hit,false);assert.equal(s.enemies[0].evasionFailure,false);
 s.purchasedPerks.waku=['next-frame'];assert.equal(attack(s,faces(4,4,4,4,4,4,1,6,6,4,1)).hit,false);assert.equal(s.enemies[0].evasionFailure,false);
});
test('full-screen automatic hit does not invent critical bonuses or consume an unrolled evasion',()=>{const s=ready(['waku']);s.accuracyLevels.waku=100;s.purchasedPerks.waku=['full-screen-hurtbox'];s.enemies[0].hp=s.hp=1e6;s.enemies[0].evasionFailure=true;const e=attack(s,faces(4,4,4,4,1));assert.equal(e.automaticHit,true);assert.equal(e.hit,true);assert.equal(e.doubleHit,false);assert.equal(e.accuracy,null);assert.equal(s.enemies[0].evasionFailure,true);});
test('tordeliese poison upgrades move to accuracy/action and annihilation has only conditional +40',()=>{const s=ready(['tordeliese']);s.levels.tordeliese=150;s.purchasedPerks.tordeliese=['greedy-gale','severing-storm','demonic-hammer','annihilation','folding-gale','for-whom-the-storm'];assert.equal(E.attackProfile(s,c('tordeliese')).poisonDamage,8);assert.equal(E.stats(s,c('tordeliese')).flat,13);s.accuracyLevels.tordeliese=25;s.actionLevels.tordeliese=100;const p=E.attackProfile(s,c('tordeliese'));assert.equal(p.poisonDamage,16);assert.equal(p.doubleHitDamage,40);assert.equal(E.accuracySpec(s,c('tordeliese')).flat,32);assert.equal(E.actionPower(s,c('tordeliese'),13),150);E.selectSession(s,'scarecrow');assert.equal(E.attackProfile(s,c('tordeliese')).ignoreDefense,false);});
test('annihilation applies forty before scaling only on double hit',()=>{const s=ready(['tordeliese']);s.levels.tordeliese=150;s.purchasedPerks.tordeliese=['annihilation'];s.enemies[0].hp=s.hp=1e6;const e=attack(s,faces(4,4,4,4,2,4));assert.equal(e.doubleHit,true);assert.equal(e.damage,B.rolledDamage(E.attackProfile(s,c('tordeliese')),13+4+40));const normal=attack(s,faces(4,4,4,4,4));assert.equal(normal.doubleHit,false);assert.equal(normal.damage,B.rolledDamage(E.attackProfile(s,c('tordeliese')),13));});
test('one-shot evasion status survives save/session switches and clears on challenge change',()=>{const s=ready(['waku']);s.enemies[0].evasionFailure=true;assert.equal(S.decode(S.encode(s)).enemies[0].evasionFailure,true);E.selectSession(s,'scarecrow');E.selectSession(s,'mohican-solo');assert.equal(s.enemies[0].evasionFailure,true);s.questActiveLevels[s.sessionId]=1;s.questLevels[s.sessionId]=2;E.setQuestLevel(s,s.sessionId,2);assert.equal(s.enemies[0].evasionFailure,false);});
test('old plot armor refunds once when its new armor requirement is not met',()=>{const s=ready(['max']);s.actionLevels.max=50;s.purchasedPerks.max=['plot-armor'];const doc=JSON.parse(S.encode(s));doc.schemaVersion=31;const old=S.decode(JSON.stringify(doc));assert.deepEqual(old.purchasedPerks.max,[]);assert.equal(old.factors,s.factors+10000000);assert.equal(S.decode(S.encode(old)).factors,old.factors);doc.state.armorLevels.max=50;assert.deepEqual(S.decode(JSON.stringify(doc)).purchasedPerks.max,['plot-armor']);assert.equal(E.perks(old,c('max')).find(p=>p.id==='plot-armor').unlocked,false);});
test('concentration is in formation dialog, drafts cancel safely and save together',()=>{const s=ready();s.paused=true;const h=harness(s);assert.ok(!h.get('quest-list').innerHTML.includes('concentration-panel'));assert.ok(!h.get('quest-list').innerHTML.includes('quest-area'));assert.ok(h.get('formation-concentration').innerHTML.includes('concentration-panel'));const open=()=>h.get('quest-list').listeners.get('click')({target:{closest:sel=>sel==='[data-formation-open]'?{dataset:{formationOpen:'mohican-solo'}}:null}});open();h.get('formation-dialog').listeners.get('input')({target:{dataset:{concentration:'mohican-solo',stat:'attack'},type:'range',value:'3'}});assert.equal(h.saved().concentration['mohican-solo'].attack,0);h.click('formation-save');assert.equal(h.saved().concentration['mohican-solo'].attack,3);open();h.get('formation-dialog').listeners.get('input')({target:{dataset:{concentration:'mohican-solo',stat:'attack'},type:'range',value:'7'}});h.click('formation-cancel');assert.equal(h.saved().concentration['mohican-solo'].attack,3);});
test('finite Jewel burst keeps all eight frames before returning to idle',()=>{const s=ready(['jewel'],'scarecrow');s.questActiveLevels.scarecrow=1;s.questLevels.scarecrow=60;E.setQuestLevel(s,'scarecrow',60);const h=harness(s,undefined,{combatRandom:()=>.5});h.click('attack');h.advance(100);h.click('attack');h.advance(550);assert.equal(h.get('jewel-combatant').classList.contains('bursting'),true);h.advance(450);assert.equal(h.get('jewel-combatant').classList.contains('bursting'),false);});




