const fs=require('fs'),path=require('path'),{performance}=require('perf_hooks');const root=path.resolve(process.argv[2]||path.resolve(__dirname,'..')),E=require(root+'/js/engine'),D=require(root+'/js/data'),S=require(root+'/js/save');
function setup(kind){const s=E.createState(1000);s.factors=1e16;E.refreshQuestUnlocks(s);for(const q of D.sessions)E.setFormation(s,q.id,[]);for(const id of ['meta','waku','jewel','megumin','richter']){s.levels[id]=kind==='high'?2000:260;}E.setFormation(s,kind==='duo'?'egg-or-chicken':'mohicans',['meta','waku']);if(kind==='multi'){E.setFormation(s,'ozmorn',['richter']);E.setFormation(s,'dementor',['jewel']);E.setFormation(s,'egg-or-chicken',['megumin']);}E.selectSession(s,kind==='duo'?'egg-or-chicken':'mohicans');for(const c of D.characters)if(s.levels[c.id])s.health[c.id]={hp:E.maxHP(s,c),status:'active',regenSeconds:0};return s;}
const random=()=>{let seed=17429;return()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32);};
const out=[];function measure(kind,name,count,fn){const start=performance.now();for(let i=0;i<count;i++)fn(i);const ms=performance.now()-start;const row={kind,name,count,ms,perCall:ms/count};out.push(row);console.log(JSON.stringify(row));}
for(const kind of ['single','multi','high','duo']){let s=setup(kind);measure(kind,'totalDps warm',50,()=>E.totalDps(s));measure(kind,'advance 100ms',100,()=>E.advance(s,.1,random(),false));measure(kind,'serialize+validate',30,()=>S.encode(s));const storage={getItem:()=>null,setItem:()=>{}};measure(kind,'persist mock storage',30,()=>S.persist(storage,s));
for(const seconds of [600,3600,28800])measure(kind,'offline '+seconds+'s',1,()=>{const copy=setup(kind);E.advance(copy,seconds,random(),false,true);});}
const {harness}=require(root+'/tests/app-harness.cjs');for(const kind of ['single','multi','high']){const start=performance.now(),h=harness(setup(kind));h.advance(10000);out.push({kind,name:'DOM harness 10s',ms:performance.now()-start,metrics:h.metrics});}
fs.writeFileSync(process.argv[3]||'performance-bench.json',JSON.stringify({out,memory:process.memoryUsage()},null,2));
module.exports={setup,random};
